### ISSUE TITLE
Provide option of unshuffled dataset

### ISSUE THREAD

**Issue by nggary** [rodrigopivi/Chatito#10]
Shuffled dataset is difficult to do the manual checking based on intention, I would suggest that to provide the option (e.g checkbox) to disable shuffling.

**Comment by rodrigopivi** [comment]
I think the shuffling is just part of the online IDE, for more real case scenarios you should be able to just use the JS api where there is no shuffle done, here is an example of how i use it https://github.com/rodrigopivi/pia_es/blob/master/build.js
