### ISSUE TITLE
How to use with regular expression features in Rasa?

### ISSUE THREAD

**Issue by tuptaker** [rodrigopivi/Chatito#11]
Hi, given an intent to pass my age to my bot, how would I do this with chatito?

In other words:
Sentence -> I am 59 years old
Intent -> "inform_age"
Slots: { age: 59 }

I thought along the lines of: 
%[inform_age]
I am @[age] years old
@[age]
??

Any help or guidance greatly appreciated.

**Comment by rodrigopivi** [comment]
this library is just for the generation of valid training examples, it does not deal with the regex features of rasa_nlu, i would suggest you to try the ner_duckling component at the rasa pipeline and also you can just add the regex you wish manually at the rasa config file, this library does not limit you on that.

**Comment by rodrigopivi** [comment]
hi @tuptaker,

BTW, this is how i would do it:
```
%[informAge]
    I am @[age] years old

@[age]
    ~[33]
    ~[22]

~[33]
    33
    thirty three

~[22]
    22
    twenty two
```

hope that helps, thanks for the feedback!

**Comment by tuptaker** [comment]
Terrific, thank you @rodrigopivi.
