### ISSUE TITLE
mark entities in sentences

### ISSUE THREAD

**Issue by albertotonon** [rodrigopivi/Chatito#15]
I'm currently facing this issue: I made a chatito file that contains all I need to generate my dataset and I'm very happy with it. However, there are a few sentences I want to add in which the entity mentions only make sense in that context and I don't want it them be reused. I would like anyway to mark such slots by using the DSL so that the entity is included in my RASA NLU training file.

Example:
`my parcel should be delivered in @[delivery_time] days` 
versus
`my parcel should be delivered as fast as possible` where "as fast as possible" is also a delivery time but I don't want to use that expression in other sentences.

Is there any way to achieve this?

**Comment by rodrigopivi** [comment]
hi, maybe some of this ways work for you?:
```
%[x]
    my parcel should be delivered @[delivery_time] 

@[delivery_time]
    in 3 days days
    as fast as possible
```
or
```
%[x]
    my parcel should be delivered in @[delivery_time] days
    my parcel should be delivered as fast as possible

@[delivery_time]
    3 days
```
let me know if any of this works for you or what specific need you have

**Comment by albertotonon** [comment]
thanks for your answer, both ways do not work in my case or in general, unfortunately. 
Option 1 works in that specific case but I cannot generalise it to other datasets since it's not always possible to rephrase sentences as you did :(
Option 2 does not mark "as fast as possible" as a slot.
What I think could be a very nice feature for chatito is the possibility of declaring templates such as
```
%[x]
  my parcel should be delivered in @[delivery_time] days
  my parcel should be delivered @[delivery_time as fast as possible]
```
Where in the second option both the slot type and the string are specified. What do you think?
I would code it myself but, unfortunately, I've never used JS :(

**Comment by rodrigopivi** [comment]
ahh i see your point @albertotonon , let me think about this use cases a bit more, but something like this could work:
```
%[x]
  my parcel should be delivered in @[delivery_time|variation1]
  my parcel should be delivered @[delivery_time|variation2]

@[delivery_time|variation1]
    3 days
    5 hours

@[delivery_time|variation2]
    as fast as possible
    quickly
```

Would need to implement this kind of custom argument variations to be able to combine sentences more selectively but also map to the same entity name

**Comment by albertotonon** [comment]
thanks for your prompt answer. Looking forward to the new version of chatito!

**Comment by rodrigopivi** [comment]
@albertotonon version 2.0.0 is released and this is fixed now, please read the docs, cheers
