### ISSUE TITLE
Synonyms are generated in the online editor, but not in the command line.

### ISSUE THREAD

**Issue by ehamerski** [rodrigopivi/Chatito#18]
Synonyms are generated in the online editor, but not in the command line.

test.chatito (the default example from online editor):
[test.chatito.txt](https://github.com/rodrigopivi/Chatito/files/2014961/test.chatito.txt)

The result from online editor (for rasa output):
[result_online_editor.json.txt](https://github.com/rodrigopivi/Chatito/files/2014962/result_online_editor.json.txt)

The result from command line (npx chatito test.chatito --format=rasa):
[result_command_line.json.txt](https://github.com/rodrigopivi/Chatito/files/2014963/result_command_line.json.txt)

The first generates synonyms:
"entity_synonyms": [{"value": "los angeles", "synonyms": ["la"]}],

But the second don't ...
"entity_synonyms": [],

Any thoughts?

**Comment by ehamerski** [comment]
Duplicated. See #16.

**Comment by ehamerski** [comment]
It seems the problem is related to the file format / new line character(s). Dos/Windows format uses \r\n as new line characters ([CR][LF]). Unix format uses only \n as new line character ([LF]). The synonyms are not generated when chatito file is encoded as dos/windows file format. 

Dos/Windows format and result (without synonyms):
[test.dos_format.chatito.txt](https://github.com/rodrigopivi/Chatito/files/2015387/test.dos_format.chatito.txt)
[result_dos_format.json.txt](https://github.com/rodrigopivi/Chatito/files/2015388/result_dos_format.json.txt)

Unix format and result (with synonyms):
[test.unix_format.chatito.txt](https://github.com/rodrigopivi/Chatito/files/2015393/test.unix_format.chatito.txt)
[result.unix_format.json.txt](https://github.com/rodrigopivi/Chatito/files/2015394/result.unix_format.json.txt)

Chatito generates dos/windows file format.

**Comment by joaodotneto** [comment]
Thanks for the answer. I'll try it here.

**Comment by rodrigopivi** [comment]
yeah it looks like a bug for windows, currently working on a re-implementation of chatito to get a lot of improvements in performance, but it may take some weeks to get there... stay tuned

**Comment by joaodotneto** [comment]
Yeah, i replace the [CR][LF] to use only [LF] and works like a charm.
Thanks for the answer my friend.

**Comment by rodrigopivi** [comment]
this should be fixed now with the 2.0.0 release, thanks!
