### ISSUE TITLE
Unable to handle repeated entities in a sentence

### ISSUE THREAD

**Issue by ShaktiKShrivastava** [rodrigopivi/Chatito#19]
Hi,

The following code

_%[lookForRoom]
    find all restaurants in @[areaName] from @[bookTime] to @[bookTime]
@[bookTime#snips/datetime]
    10
    11
@[areaName]
    North Avenue
    commerical street_

generates,

`{
  "rasa_nlu_data": {
    "regex_features": [],
    "entity_synonyms": [],
    "common_examples": [
      {
        "text": "find all restaurants in North Avenue from 10 to 11",
        "intent": "lookForRoom",
        "entities": [
          {
            "start": 24,
            "end": 36,
            "value": "North Avenue",
            "entity": "areaName"
          },
          {"start": 48, "end": 50, "value": "10", "entity": "bookTime"}
        ]
      },...`

You would notice that only one occurrence of bookTime is being reflected in the generated dataset.
A workaround is to make two entities of bookTime1 and bookTime2, but its simply an overburden to copy paste the same thing twice.

**Comment by rodrigopivi** [comment]
will take a deeper look at this, are you under windows environment? currently working on a re-implementation of chatito to get a lot of improvements, but it may take some weeks to get there... stay tuned

**Comment by ShaktiKShrivastava** [comment]
Hi, I am using Mac. 
A workaround until the next release is to use different entity names with the same definition. Something like,
`%[lookForRoom]
find all restaurants in @[areaName] from @[bookTime1] to @[bookTime2]
@[bookTime1#snips/datetime]
10
11
@[bookTime2#snips/datetime]
10
11
@[areaName]
North Avenue
commerical street`

**Comment by rodrigopivi** [comment]
this should be fixed now with the release of 2.0.0
