### ISSUE TITLE
Chatito online

### ISSUE THREAD

**Issue by hpgsantos** [rodrigopivi/Chatito#2]
Hi may be this is not the best place, but I'm getting error on Chatito online in this request:

https://rawgit.com/rodrigopivi/Chatito/master/core/datasetGenerator.js

Best regards

**Comment by rodrigopivi** [comment]
Hi @hpgsantos,
Thanks for reporting, accessing https://rawgit.com/rodrigopivi/Chatito/master/core/datasetGenerator.js works for me, maybe you can try again, will close this issue as i've tested in many devices and works fine
