### ISSUE TITLE
regex extractor

### ISSUE THREAD

**Issue by Souldiv** [rodrigopivi/Chatito#20]
hey,
i wanted to know how do you use regex extractor with chatito, do you have any example?

**Comment by rodrigopivi** [comment]
Hi,

sure, you can first create a json  file declaring your regex features e.g.: (rasaOptions.json)
```
{
    "rasa_nlu_data": {
        "regex_features": [
            {
                "name": "zipcode",
                "pattern": "[0-9]{5}"
            },
            {
                "name": "greet",
                "pattern": "hey[^\\s]*"
            }
        ]
    }
}
```

Then you can create your dsl definition, a file like `example.chatito` and then run (given chatito is installed as npm package):

```
npx chatito example.chatito --format=rasa --formatOptions=rasaOptions.json
```

Cheers

**Comment by iobreaker** [comment]
Hi,

Any example how to do this using chatito IDE please

Regards
