### ISSUE TITLE
How to create test set with online tool?

### ISSUE THREAD

**Issue by GomesAle** [rodrigopivi/Chatito#23]
I remember the online tool had the option to create train set and test set, but now I only can see train set. There is some way to create test sets?

**Comment by arnabanerji** [comment]
I'd like to bump this, it was a really useful feature until it disappeared a few days ago.

**Comment by rodrigopivi** [comment]
will add that functionality back soon

**Comment by rodrigopivi** [comment]
@GomesAle @arnabanerji 

Thanks for your feedback, just released v 2.1.0 with support for test dataset again, now its part of the dsl itself at the intents definition, feel free to check the new online ide for examples on how this work, thanks!
