### ISSUE TITLE
Multiple intents

### ISSUE THREAD

**Issue by AlvaroMonteagudo** [rodrigopivi/Chatito#25]
How could I use declared intents to generate a combined one: Graphic example:
```
%[greet]
    Hola
    Ey
    Buenas
    Buenos días
    Buenas tardes
    Buenas noches

%[inform]
    Mi nombre es @[nombre]
    Me llamo @[nombre]
    Puedes llamarme @[nombre]

%[greetandinform]
    %[greet] %[inform]

```
So i can automatically generate the Rasa multiple intents like: greet+ask_question, happy+thankyou...
That at the moment is not working or I may using the wrong syntax, any help is welcome thank you.
(if relevant): I am using online IDE

**Comment by rodrigopivi** [comment]
hi @AlvaroMonteagudo,
atm i am against adding nesting to intents, the DSL wont prevent you from writing a custom adapter to generate two intents, something like, for example you can add something like:
```
%[greet]
   ~[greet]

%[inform]
   ~[mi nombre] @[nombre]

%[greet AND inform]
    ~[greet] ~[mi nombre] @[nombre]

~[mi nombre]
    Mi nombre es
    Me llamo
    Puedes llamarme

~[greet]
    Hola
    Ey
    Buenas
    Buenos días
    Buenas tardes
    Buenas noches
```

i think this is more or less what you want to do.. yeah there is still some repetition, maybe adding slots inside alisases would help reduce the code..

now once you have this DSL you can write your own custom adapter using the npm package (use the rasa adapter as reference: https://github.com/rodrigopivi/Chatito/blob/master/src/adapters/rasa.ts), then the name of the intent can be split by the ` AND ` key and you generate two intents, does this help you?

**Comment by rodrigopivi** [comment]
@AlvaroMonteagudo 

Thanks for your feedback, just released v2.1.0 with support for the `+` at the intent definition names, this should now work out of the box by default, feel free to reopen the issue if you have any other issues on this topic, thanks!

**Comment by munaAchyuta** [comment]
Hi,
can we have model which can generate distinguished sentence with intent from given input text.
like below example :
"Turn the bathroom light off and remind me to take the trash out."
There are two independent intents here:
turn_lights, set_reminder.
similarly another example : "Hey what's up? do you guys offer free trial?"
there are two intents here : greetings , product_pricing

Thanks & Regards,
Achyuta nanda Sahoo

**Comment by rodrigopivi** [comment]
hi @munaAchyuta 

if you are working with Rasa multi intents, an example like this should work:
```
%[greet]("training": "1")
    ~[greet]

%[inform]("training": "1")
    ~[my name is] @[name]

%[greet+inform]("training": "1")
    ~[greet] ~[my name is] @[name]

~[my name is]
    my name is
    you can call me
    i'm

~[greet]
    hi
    hello

@[name]
    achyuta
    muna
```
