### ISSUE TITLE
Custom entities with v2

### ISSUE THREAD

**Issue by YuukanOO** [rodrigopivi/Chatito#26]
When using chatito version 1.*, we can easily define entity per slot with the `#` notation, something like `@[date#snips/datetime]`.

I do not know how to do the same thing with the new version of chatito. Maybe I should use the trainingOptions file but I can't find documentation on how to do it.

**Comment by rodrigopivi** [comment]
Hi @YuukanOO 

Yes, now the hash char is used to denote a variation of the slot, you can read about it at the docs. The #snips/datetime functionality is no longer supported in v2 because it is a snips only feature and is not related to the DSL itself, you can just post process the dataset generated to fit your needs adding the extra tags as you wish to the slots you want, you can also submit a PR for the snips adapter (https://github.com/rodrigopivi/Chatito/blob/master/src/adapters/snips.ts) to explore ideas on how to implement this, but my initial intuition is that the dsl itself needs no change for this functionality

**Comment by YuukanOO** [comment]
I understand your take on that.

Is there any way to add comments to the DSL spec? I imagine something like docstrings that could be parsed by adapters.

With that kind of feature, there is no need to extend the dsl beyond what it has been made for.

What do you think?

**Comment by rodrigopivi** [comment]
i would go against that kind of practice where you need to parse something manually, i am considering a way to add extra properties to slot entities, but for now, one thing you can do, and can be implemented just on the snips adapter, is to use some kind of special keyword convention that the adapter can match and just replace to add the custom snips tags, something like `@[__date__week days]`, then the adapter can match the `__date__`

**Comment by YuukanOO** [comment]
Sounds good to me but it looks like `/` is considered as a SyntaxError.

So `@[dateFrom__snips/datetime]` does not work 🤔

**Comment by YuukanOO** [comment]
Or we could handle entity properties with a syntax like `@[dateFrom](entity=snips/datetime, another_property=42)` that will be made available to adapters.

**Comment by rodrigopivi** [comment]
try something like @[city__date] and adapt the snips adapter or create your own post processor to fit your needs. the last idea yeah i thought about it too, its just that it adds extra complexity to the dsl that helps in some edge cases, but most of the times are simple stuff you can just add on a post process custom function (like add 5 lines of code) to create your own adapter to fit the needs of your model, im not sure it is such a big cost, but i will still consider the attaching of custom properties like you described, thanks!

**Comment by rodrigopivi** [comment]
@YuukanOO,

Thanks for your great feedback, Chatito v2.1.0 now comes with custom entity arguments for intents and slots, so now you should be able to attach any property to those entities and open possibilities for extending custom adapters, like adding rasa dialog generation support from the chatito dsl. hope this is now enough for most use cases on most nlu models, let me know if have other issues or feedback, thanks!
