### ISSUE TITLE
Output generation warning

### ISSUE THREAD

**Issue by hpgsantos** [rodrigopivi/Chatito#3]
During execution of this DLS the output start/end position is not correct

%[findBoletoDASByMes]
    ~[greet]? ~[botName]? ~[please]? ~[find]? @[boleto]? @[mes]

~[greet]
    oi
    ola
    opa
    bom dia

~[botName]
    mago
    Mago

~[please]
    por favor
    poderia
    pode
    gostaria
    quero

~[find]
    gerar
    emitir
    imprimir
    pagar

@[boleto]
    boleto
    DAS
    contribuicao

~[janeiro]
    janeiro
    Janeiro
    janero
    jan
    01

~[fevereiro]
    fevereiro
    feverero
    fev
    02

@[mes]
    ~[janeiro]
    ~[fevereiro]

**Comment by rodrigopivi** [comment]
Atm the DSL requires a 4 space identation for inner block code. This works:

```
%[findBoletoDASByMes]
    ~[greet]? ~[botName]? ~[please]? ~[find]? @[boleto]? @[mes]

~[greet]
    oi
    ola
    opa
    bom dia

~[botName]
    mago
    Mago

~[please]
    por favor
    poderia
    pode
    gostaria
    quero

~[find]
    gerar
    emitir
    imprimir
    pagar

@[boleto]
    boleto
    DAS
    contribuicao

~[janeiro]
    janeiro
    Janeiro
    janero
    jan
    01

~[fevereiro]
    fevereiro
    feverero
    fev
    02

@[mes]
    ~[janeiro]
    ~[fevereiro]
```

**Comment by rodrigopivi** [comment]
Thanks for reporting, it was indeed a bug when the first word was an argument and had optinoal previous aliases, fixed it here https://github.com/rodrigopivi/Chatito/commit/2cf99db7cd39816843c032336909dfc4325ac6b9 and added your example as a test too. Please let me know if you have any more issues, closing this for now.
