### ISSUE TITLE
Node module gives error: `Unexpected token {`

### ISSUE THREAD

**Issue by nielsrolf** [rodrigopivi/Chatito#34]
I installed chatito locally and after that globally. If I run it on a file that works with the online IDE, I get this error:

 ```
>> npx chatito data/chatito/search.chatito 
Unexpected token {
>>
```

Is the node module broken?

**Comment by rodrigopivi** [comment]
hi @nielsrolf 

Pleas provide the npm package version you are using and if possible a DSL code snippet i can use to reproduce the issue

**Comment by nielsrolf** [comment]
These are the versions:

```
>> npx chatito data/chatito/search.chatito
Unexpected token {
>> npm --version
3.5.2
>> npx --version
10.2.0
>> npm list -g | grep chatito
├─┬ chatito@2.1.4
```

And this is the content of `data/chatito/search.chatito` is

```
>> cat data/chatito/search.chatito
%[search]('training': '1')
    hello

```

**Comment by rodrigopivi** [comment]
what is your nodejs version, can't reproduce the error atm

**Comment by nielsrolf** [comment]
Ups that was the issue, it was v4.2.6. I updated it, now it works. Thanks
