### ISSUE TITLE
Define entity in non top level element does not work

### ISSUE THREAD

**Issue by nielsrolf** [rodrigopivi/Chatito#35]
This is probably a feature request, unless this feature should work already. I would like to define an entity in a not top level element:

```
%[search]('training': '4')
    ~[greet?] ~[request] ~[thanks?]

~[greet]
    hi
    hello

~[thanks]
    thanks
    thx

~[request]
    I want a @[product]
    Give me a @[product]

@[product]
    ~[shoe]
    ~[shirt]

~[shoe]
    shoe
    cool shoe

~[shirt]
    shirt
    tshirt
```

It gives this sample

```
{
    "rasa_nlu_data": {
        "regex_features":[],
        "entity_synonyms":[],
        "common_examples":[
            {"text":"I want a @[product]","intent":"search","entities":[]}
        ]
    }
}
```

If I put `@[product]` in the top level element, it works fine. Changing the first part to

```
%[search]('training': '1')
    ~[greet?] I want a @[product] ~[thanks?]
```

gives
"I want a shoe thanks".

Is this possible in some way?

**Comment by rodrigopivi** [comment]
Thanks for the suggestion @nielsrolf, yes. this feature it is not part of the spec at the moment to make things simple, but i have to agree this is an interesting and helpful feature for larger datasets, will consider this as an interesting addition for the next version, feel free to start a PR adding this functionality if you need this feature very soon

**Comment by nielsrolf** [comment]
I made a quick work around for rasa, it's a script that runs chatito once, generates new chatito files from the train data where the slots are moved to the top level (because the train data looks like "I want a @[product]"), then runs it again. It's [here](https://github.com/nielsrolf/double_chatito)
