### ISSUE TITLE
Improvement of displaying error

### ISSUE THREAD

**Issue by nggary** [rodrigopivi/Chatito#4]
Sometime the error shows "Expected \"%\", \"@\", \"\\n\", \"~\", correct indentation, or end of input but \" \" found."  But it never say which line found the error. Could you please add the line number into error message?

**Comment by rodrigopivi** [comment]
Done. Now the lib is showing the full pegjs error report.

**Comment by tuptaker** [comment]
Hey Rodrigo, sorry to bump this thread, but I'm not getting the line number for the errors, and I just installed Chatito a week ago. Any tips? I've got a large chatito file I'm trying to convert, but I keep getting:
ERROR Expected "%", "@", "\n", "\r\n", "~", correct indentation, or end of input but "[" found.

At this point, I'm just guessing where the error might actually be, but haven't nailed it down yet.

**Comment by rodrigopivi** [comment]
@tuptaker you can always check your dsl at the online IDE. Also just released version 1.2.0 of the npm package with better error reporting, but there are breaking changes, like now optional arguments have a different syntax plus we generate full rasa and snips nlu datasets, not just the examples like before.
