### ISSUE TITLE
implemantation of lookup tables for rasa_nlu

### ISSUE THREAD

**Issue by schwepmo** [rodrigopivi/Chatito#42]
Hey,
with rasa_nlu 0.13.3 rasa introduced lookup tables, which have a similar notation
as synonyms.
Correct me if I'm wrong, but I don't think Chatito offers a way to specify lookup tables yet.
I think it would be a nice feature to add.
Cheers

**Comment by rodrigopivi** [comment]
hi @schempo

This is something that will be implemented for the next version, atm im with some work load, so this may take some weeks, meanwhile, you can use the generated parser utility to get the AST object.

An example of this is at the parser tests https://github.com/rodrigopivi/Chatito/blob/master/src/tests/parser.spec.ts

**Comment by schwepmo** [comment]
hey @rodrigopivi,
yeah sure no hurries. I've got some freetime on my hands this month. I'll maybe
try to read into the code and open a PR. :)
cheers

**Comment by rodrigopivi** [comment]
did a quick research on this topic, adding lookup tables won't be considered ATM since most of the datasets generated by Chatito are non deterministic.
