### ISSUE TITLE
Generate and download data set gives empty JSON file

### ISSUE THREAD

**Issue by jcopps** [rodrigopivi/Chatito#43]
The preview shows proper tree structure having valid cases. 
However upon downloading the JSON file, I get to see nothing. 
Attached the grammar file for investigation.

[rules.txt](https://github.com/rodrigopivi/Chatito/files/2449719/rules.txt)

**Comment by schwepmo** [comment]
Hey I just tried adding newlines after each of your Entities
and got it to generate the training data. Let me know if this
helped. (I attached the generated training data as a txt-file since
github doesn't accept json-files)
[training_dataset_1539100313.txt](https://github.com/rodrigopivi/Chatito/files/2461189/training_dataset_1539100313.txt)

**Comment by jcopps** [comment]
Where is the newline needs to be added? 
Example?

**Comment by jcopps** [comment]
// Find restaurants by city
%[weather]('training': '100')
    ~[greet?] ~[whats?] ~[the?] ~[weather] ~[located at] @[ENTITY_location?] @[ENTITY_temporal?]
    ~[greet?] ~[ask?] ~[the?] ~[weather] ~[located at] @[ENTITY_location?] @[ENTITY_temporal?]
    ~[greet?] ~[ask] ~[if_it_is] ~[rain_verb] ~[located at] @[ENTITY_location] ~[city?] @[ENTITY_temporal?]
    ~[greet?] ~[ask] ~[if_it_is] ~[snow_verb] ~[located at] @[ENTITY_location] ~[city?] @[ENTITY_temporal?]

%[weather_future]('training': '100')
    ~[greet?] ~[whats?] ~[the?] ~[weather] ~[forecast] ~[located at] @[ENTITY_location?] @[ENTITY_temporal?]
    ~[greet?] ~[ask?] ~[the?] ~[weather] ~[forecast] ~[located at] @[ENTITY_location?] @[ENTITY_temporal?]
    ~[greet?] ~[ask_future] ~[if_it_is] ~[rain_verb] ~[located at] @[ENTITY_location] ~[city?] @[ENTITY_temporal?]
    ~[greet?] ~[ask_future] ~[if_it_is] ~[snow_verb] ~[located at] @[ENTITY_location] ~[city?] @[ENTITY_temporal?]

@[ENTITY_location]
    ~[new york]
    ~[san francisco]
    ~[atlanta]
    ~[rome]

@[ENTITY_temporal]
    ~[tomorrow]
    ~[now]
    ~[right now]
    ~[next week]

~[greet]
    hey
    hi
    hello
    greetings

~[located at]
    at
    in the area of
    in
    around

~[restaurants]
    restaurants
    places to eat
    where to eat

~[whats]
    whats
    what is
    how is
    hows

~[weather]
    weather
    temperature
    climate

~[forecast]
    forecast
    prediction
    estimation

~[ask]
    tell me 
    do you know
    can you tell me 
    find out

~[if_it_is]
    if it is
    is it

~[ask_future]
    can
    possible that
    how likely is
    can

~[rain_noun]
    rain
    pour
    shower

~[rain_verb]
    raining
    pouring
    showering

~[snow_noun]
    snow
    snow fall

~[snow_verb]
    snowing
    snow falling

**Comment by jcopps** [comment]
The system says "Correct syntax" for the above rule data. But I dont get to download the right content.

**Comment by schwepmo** [comment]
do you have your intents in brackets (%[weather])?
What does your JSON-file look like? Is it just empty? 
Maybe it's a problem with your browser?
You could try installing Chatito via node and run the script locally, this might also give you some error messages

**Comment by rodrigopivi** [comment]
hi @jcopps, 

I tested on chrome, and i get to download two files, the training file, containing 100 examples, and the testing file that is what you describe `{}`

So my intuition is that maybe you are not aware that you are downloading two files of maybe your browser only gets you the last download, which is the testing dataset.

**Comment by jcopps** [comment]
Thanks! Got the files now.
