### ISSUE TITLE
Use Chatito file only to declare slot ?

### ISSUE THREAD

**Issue by lyoko17220** [rodrigopivi/Chatito#44]
In my project I want to declare my slots like cities, dates etc.. in other file of my intent.

I read that is was not in standard but is it possible ?

**Comment by rodrigopivi** [comment]
hi @lyoko17220 im not sure i understand your need, is it to be able to modularize and import the slots from another file, or to only generate slots?

For the first altternative, we don't have a specification for importing other chatito files, (at the moment you may have to manually concatenate files and then generate), if it is the second alternative, you can just generate slots inside intents, and then manually post process the generated dataset, you may want to share your use case.

**Comment by lyoko17220** [comment]
I'd like to organise my folder structure like this :

- /datasets
  - /entities
    - cities.chatito
  - /language
    - /english
      - searchRestaurantByCity.chatito
      - searchContactByCity.chatito



Chatito command would be : `npx chatito datasets --format=snips  --outputPath=output/`

In my example `searchRestaurantByCity` and `searchContactByCity` will use City entity but we can't do that. We have to reimplement City entity in each Intent.

If I try this configuration there are 2 errors
1. "No action found" on cities.chatito
2. "Slot not defined: city" on my Intent files

**Comment by rodrigopivi** [comment]
i see your use case, adding recursive searching for chatito files and imports of other chatito files for reusing entity declarations is a nice addition for future chatito releases, at the moment the only solution you have is to copy the contents of one fine into the other

**Comment by lyoko17220** [comment]
Okay thanks. I'm looking forward of this implementation. Nice work !

**Comment by jamesmf** [comment]
This would be great functionality! it's a useful tool, and allowing you to modularize would make it a lot easier to use in larger applications with many moving parts.

**Comment by rodrigopivi** [comment]
file imports and reusing entity declarations is now implemented in 2.2.0
