### ISSUE TITLE
Too many duplicates

### ISSUE THREAD

**Issue by jonpok** [rodrigopivi/Chatito#45]
Hi,

when trying to generate 'rasa_dataset_training.json' I get this message:

Too many duplicates while generating dataset! Looks like we have probably reached the maximun ammount of possible unique generated examples. The generator has stopped at 4385 examples for intent timeOff.

Any ideas how to avoid this?

**Comment by rodrigopivi** [comment]
hi @jonpok use the entity arguments for `training` and `testing`, they are designed for that use case, read the docs about them

**Comment by rodrigopivi** [comment]
Chatito is meant to generate non deterministic datasets, so generating all variations for a big dataset is not recommended, the too many duplicates warning is ok atm.
