### ISSUE TITLE
Rasa to Snips converter

### ISSUE THREAD

**Issue by AsyncSan** [rodrigopivi/Chatito#46]
"format" 
and
"formatOptions"

seem to indicate that one can convert rasa to snips format with the command line tool.
But I couldnt get it to work yet. Is there something wrong or is that not intendet as a converter?

Greetings

**Comment by rodrigopivi** [comment]
hi @AsyncSan,

We don't support rasa to snips convert, chatito supports generating from chatito grammar definitions to rasa or snips, chatito is not a converter.
