### ISSUE TITLE
incorrect synonyms value 

### ISSUE THREAD

**Issue by kishanbajaj** [rodrigopivi/Chatito#49]
As per RASA, synonyms are generated when you return a single value for different texts:

![screen shot 2018-11-05 at 5 07 35 pm](https://user-images.githubusercontent.com/5063296/47996088-5fa8cf80-e11d-11e8-9a68-050bb4f98531.png)

I want to establish the same using Chatito:

![screen shot 2018-11-05 at 5 19 25 pm](https://user-images.githubusercontent.com/5063296/47996576-02ae1900-e11f-11e8-8469-90942ee19408.png)

Output is not as expected:

![screen shot 2018-11-05 at 5 16 33 pm](https://user-images.githubusercontent.com/5063296/47996446-9e8b5500-e11e-11e8-9be1-b23e33aa08d5.png)

The "value" should have been same in all cases.

**Comment by rodrigopivi** [comment]
hi @kishanbajaj 

Have you tried training first then testing? it should work fine after training, as you described, please try it first.

**Comment by kishanbajaj** [comment]
Hi @rodrigopivi ,

Yes, it does. :) This might have been changed in the latest version because this did not work in earlier versions of RASA.

I will close this issue.
