### ISSUE TITLE
Feature Request: ability to turn off rasa synonym behavior

### ISSUE THREAD

**Issue by jamesmf** [rodrigopivi/Chatito#50]
It would be great to be able to turn off the behavior where single-token slot becomes a synonym. While that's a cool function to have, there are definitely instances where it's undesired behavior.

For reference:
```
When an alias is referenced inside a slot definition, and it is the only token of the slot sentence, by default the generator will tag the generated alias value as a synonym of the alias key name
```

Controlling this via a flag would be awesome!

**Comment by rodrigopivi** [comment]
Slots will only consider a synonym, if an alias entity is the only entity inside the slot sentence.  You can skip that behavior simply by not using a single alias inside an slot, like:
```
%[intent]
    text @[slot] text

@[slot]
    this is not ~[a synonym] as a sentence
    ~[this is a synonym] 
```

Thanks
