### ISSUE TITLE
Feature Request : Force some specified samples to be included in output

### ISSUE THREAD

**Issue by ocatheli** [rodrigopivi/Chatito#51]
Hi,

It would be a nice feature to be able to specify into a training set some mandatory sentences to be included into the output.

For example : 
```
%[greet]('training: '2', 'testing': '1')
    hello
    hi
    hola &[training]
    salute
```

This could be useful for large sets with large combinations possibilities when you need to limit the output samples number, but you really want to have some specified samples to be included.

**Comment by rodrigopivi** [comment]
With the probability operator, now one can have more control about the expected output generation
