### ISSUE TITLE
the generate principle, i receive a many duplicates

### ISSUE THREAD

**Issue by WoWuQ** [rodrigopivi/Chatito#52]
when i generate rasa format traing data,  i get many duplicates prompt, and i do not use traing and testing limit.   I want to konw the generate principle, why can produce this phenomenon, it can not stop the current intent, and generate next intent?

**Comment by WoWuQ** [comment]
I find some my config error ,and i know some principle, thanks.

and now I want to konw, Does chatito support [~[greet]@[name]~[adv]?] config?

I mean combine many config appearance one or not？

**Comment by ocatheli** [comment]
Could you share the chatito file ?

**Comment by rodrigopivi** [comment]
The probability operator is now available since version 2.2.0, now its possible to have more control on the generation paths, that with the training and testing arguments should be enough to fix this issue
