### ISSUE TITLE
Error: Can't generate 55555555 examples. Max possible examples is 99398

### ISSUE THREAD

**Issue by praveenkumart** [rodrigopivi/Chatito#55]
Error: Can't generate 55555555 examples. Max possible examples is 99398

so i have given 99398 in  training

%[generic_intent]('training': '99398')
    @[city_name]
    @[zip_code]

then i have executed  npx chatito generic_intent.chatito --format=rasa

now file is not generated

**Comment by rodrigopivi** [comment]
this problem is because you are requesting more examples than the max possible combinations of your sentences.
