### ISSUE TITLE
[Crash] Does not survive when generator yields a variation with just a space

### ISSUE THREAD

**Issue by ouamer-dahmani** [rodrigopivi/Chatito#56]
Hi,

I ran into an issue where generating fairly large datasets would have chatito crash inside of `chatitoFormatPostProcess`.

I had trouble debugging because this ran in a separate process but after instrumentation of the code I ended up finding the cause: the variation generator creates a line with just a space in it. This can happen when all entity generators end up being optional.

A simple repro:
```
%[hi]('training':'4')
    ~[crash_me]

~[crash_me]
    ~[optional?] ~[optional_too?]
```

While this may seem obvious it can happen fairly easily when one is working on large chatito files.

The crash can probably be fixed by making `chatitoFormatPostProcess` more robust but it might actually be simpler to catch blank variations upstream. You could also pop a helpful message to the user by printing `innerEntityKey` to tell them which entity caused this.

Cheers!

**Comment by rodrigopivi** [comment]
This is fixed now, if a sentence generates an empty string (like in this case because all entities are optional). Chatito will trow a more contextual error message.
