### ISSUE TITLE
is there a way to share some alias and entity definition  between many chatito files?

### ISSUE THREAD

**Issue by iorilu** [rodrigopivi/Chatito#59]
If we split files to multiple chatito files , but some slot and alias are shared, how to handle it in command line

**Comment by mminchev** [comment]
Excellent question, I am also interested in this type of functionality. I can image it something like an import statement that you can have in the beginning of a .chatito file in order to include some shared slots/entities/aliases.

**Comment by mminchev** [comment]
This issue is similar to #44 .

**Comment by Pennsy** [comment]
I am using chatito to generate data for rasa, also wondering how to show slots and entity definition among multiple chatito files

**Comment by Andrflor** [comment]
Not possible with chatito at the momment.
Thus, you can use [https://github.com/SimGus/Chatette](chatette) wich is a chatito port to python designed for rasa that also as some more functionalities. 
Using it, you split in as many files as you want and then import all in the master file using pipe syntax specified in the wiki. You can even clone it into your project to modify it as you like.

**Comment by rodrigopivi** [comment]
Thanks for the suggestions. Chatito v2.2.0 now supports import statements and controlling the generation path's probabilities. Cheers.
