### ISSUE TITLE
Expose Chatito API to JS more fluently

### ISSUE THREAD

**Issue by SyedWasiHaider** [rodrigopivi/Chatito#6]
Hi there. Great job on this library (it is very helpful).

Is there anyway you could make it so that is easier to call Chatito from JS more fluently? What do I mean?

```javascript
var chatito = require('chatito')

output = chatito('/path/to/my/lol.chatito')
```

Just an idea.

**Comment by rodrigopivi** [comment]
Hi @SyedWasiHaider 

Thanks, will look into exposing the api more fluently, you should also be able to just require the datasetGenerator.js file, and use the exposed `datasetFromString` method.

https://github.com/rodrigopivi/Chatito/blob/master/index.html#L102

**Comment by rodrigopivi** [comment]
hi @SyedWasiHaider,

Just upgraded the lib to expose the core functions.

You can now do
```
const chatito = require('chatito');
```

You can look at https://github.com/rodrigopivi/Chatito/blob/master/core/datasetGenerator.js#L188 to get more insight at the exposed api methods. Closing this issue now, thanks!
