### ISSUE TITLE
some npm generator options invalid

### ISSUE THREAD

**Issue by Cuiqingyao** [rodrigopivi/Chatito#63]
`npx chatito ./my_chatito.chatito --format=rasa --outputPath=./test/ --traingFileName=my_custom_file.json --testingFileName=my_custom_tesing.json`

only `--format`  option can work well
`--outputPath`, `--trainingFileName`and`--tesingFileName` do not change my output files name or location

**Comment by zhangyanbo2007** [comment]
I also find this problem,can anybody solve it?

**Comment by rodrigopivi** [comment]
fixed in v2.2.0
