### ISSUE TITLE
Optional slots

### ISSUE THREAD

**Issue by Zylatis** [rodrigopivi/Chatito#68]
I know this has been addressed here
https://github.com/rodrigopivi/Chatito/issues/24

but I am unsure how to do the nesting properly and I don't see a direct example in the docs.

I have data for addresses and i want to do something like

@[suburb] @[postcode?] @[state?]

how do i do this with the nesting described in that link?

Thanks!

**Comment by rodrigopivi** [comment]
Hi @Zylatis,

That issue was to allow testing slots within aliases. Like this:

```
%[informAddress]('training': '5', 'testing': '5')
    ~[located at]

~[located at]
    @[suburb] @[postcode?] @[state?]

@[suburb]
    su1
    su2

@[postcode]
    pc1
    pc2

@[state]
    st1
    st2
```

Closing the issue. Let me know if that is enough for your use case.
