### ISSUE TITLE
Why don't aliases produce the same value?

### ISSUE THREAD

**Issue by esBeee** [rodrigopivi/Chatito#7]
First off, thanks for this project! This has the potential of saving people lots of time!
I wonder, though, if you have
```
%[lightChange]
    Hey Bot @[switch] the lights

@[switch]
    ~[off]

~[off]
    turn off
    deactivate
```
, wouldn't it make more sense if these aliases produced the same value "off", as in
```
{
    "text": "Hey Bot turn off the lights",
    "intent": "lightChange",
    "entities": [
        {
            "start": 8,
            "end": 16,
            "value": "off",
            "entity": "switch"
        }
    ]
},
{
    "text": "Hey Bot deactivate the lights",
    "intent": "lightChange",
    "entities": [
        {
            "start": 8,
            "end": 18,
            "value": "off",
            "entity": "switch"
        }
    ]
}
```
instead of different values, as it is right now, like
```
{
    "text": "Hey Bot turn off the lights",
    "intent": "lightChange",
    "entities": [
        {
            "start": 8,
            "end": 16,
            "value": "turn off",
            "entity": "switch"
        }
    ]
},
{
    "text": "Hey Bot deactivate the lights",
    "intent": "lightChange",
    "entities": [
        {
            "start": 8,
            "end": 18,
            "value": "deactivate",
            "entity": "switch"
        }
    ]
}
```
? Or what's the recommended way to handle these cases? Can you do anything else than defining the aliases again in the code that later on handles the parsed entities?

**Comment by rodrigopivi** [comment]
Hi @esBeee 

I started building this library to test with other models that are just for sequence labelling, then i found Rasa and modified the old behavior to Rasa's data format. This suggestion makes a lot of sense now, i think we can find a way to express that type of relationship in the DSL i think i can build a PR for that soon, and test its performance for training.

**Comment by rodrigopivi** [comment]
@esBeee hi,

Just published version 1.1.0 of the npm package and upgraded the functionality as described, if an argument value is only an alias, the parsed argument will be the original alias, as is now described in the docs, and at the main example.

Also created an example repository to compare the trained models using the 1.0.7 dataset and the new 1.1.0 dataset, and was able to verify that RasaNlu correctly generalizes the variations as an alias/synonim

https://github.com/rodrigopivi/chatito_rasa_testing_datasets

Closing this ticket as now this issue is at master and published at npm. Thanks

**Comment by esBeee** [comment]
Sounds great! Again, thanks for this project. It is highly appreciated!

**Comment by nggary** [comment]
Sorry for comment on this closed issue, I would suggest to add back the actual value in entities, so we won't need to subtract the labeled text by start/end index, I would propose the following format:
{
    "text": "Hey Bot deactivate the lights",
    "intent": "lightChange",
    "entities": [
        {
            "start": 8,
            "end": 18,
            "label": "deactivate" // or other name 
            "value": "off",
            "entity": "switch"
        }
    ]
}

**Comment by rodrigopivi** [comment]
@gnar
