### ISSUE TITLE
Import failing

### ISSUE THREAD

**Issue by jamesmf** [rodrigopivi/Chatito#70]
The changes in `2.2.0`+ are great! But I'm having an issue using the import.

File 1, `capabilities.chatito` looks like this 

```
import ./common.chatito

%[capabilities]('training': '10', 'testing': '2')
    what can you do
    what can you help with
    ...
```

And file then `common.chatito` looks like this:
```
@[my-slot]
    value1
    value2
```

I have `v2.2.1` installed, and I get `'Expected "%", "//", "@[", "~", or end of line  but "i" found.',` one `line 1, column 1`.

**Comment by rodrigopivi** [comment]
hi @jamesmf,

Thanks for the report. I can't reproduce the error, your example works for me on the online IDE and with a fresh cli project setup.
Maybe you installed chatito npm package globally and are using an older version?, i would suggest to first confirm your example works on the online IDE, then try a fresh npm install of the package. Let me know if that works.

**Comment by jamesmf** [comment]
Totally right, just a `chatito` vs `npx chatito` issue on my end. Thanks, these upgrades are incredibly useful!
