### ISSUE TITLE
Snips NLU output format error 

### ISSUE THREAD

**Issue by TrevorFung** [rodrigopivi/Chatito#73]
**Short:** 
In Snips JSON output, `"synonyms":[{}]` should be `"synonyms":[]` to avoid throwing error of Python dictionary objects having no strip function

**Conditions under which error encountered:**
- Python 3.7.2
- Snips 0.19.7
- Chatito online IDE output .json file, specifically the `@city` portion
- Date: 6/23/19

**Comment by rodrigopivi** [comment]
Thanks for the report @TrevorFung fixed in 2.3.0.
