### ISSUE TITLE
数据量太大，然后速度太慢了

### ISSUE THREAD

**Issue by freecui** [rodrigopivi/Chatito#77]

**Comment by freecui** [comment]
我有个文件用了25万的数据量，然后在线的ide就非常卡

**Comment by rodrigopivi** [comment]
Hi @freecui , I don't speak Chinese but Google Translates this:
```
The amount of data is too large, then the speed is too slow
```
and
```
I have a file with 250,000 data, and then the online ide is very card.
```
So i think that maybe you should start using the npm cli tool on top of VS-Code (there is a vs code syntax plugin), the IDE is just to get started. Besides that, the limit should be the computer ram memory, and at that point you should be able to split your dataset entry points. Hope that helps.
