### ISSUE TITLE
How can I add Number?

### ISSUE THREAD

**Issue by sujeongHeo** [rodrigopivi/Chatito#79]
Hi, I really appriciate  to ask you for RASA nlu dataset.
I just wonder if there is any expression for Number entities.

For example ,  

kids under 7 is free?
I want to make big data for **number, 7**
kids under 1 is free?
kids under 2 is free?

etc...

Please help me if you have any idea for this.

Sincerely

Sujeong.

**Comment by sujeongHeo** [comment]
for example ,

**Comment by rodrigopivi** [comment]
Hi @sujeongHeo 

Pre defined entities are not provided by default. It may be interesting addon as another project to have some utilities like predefined numbers but for now you will have to define those aliases manually. Like:

```
%[intent]
    kids under ~[ageUnder] is free?

~[ageUnder]
    1
    one
    2
    two
    3
    ...
```
