### ISSUE TITLE
Training data produced is not in rasa format 

### ISSUE THREAD

**Issue by sameerkumar16** [rodrigopivi/Chatito#8]
Let me begin by saying "Thank you" for making this. It has potential to save a lot of time for bot makers like me. But I am facing a problem with this .The Json data produced after converting the DSL file is in another format .I would give an example
```
{
        "action": "booking",
        "id": "i want to book a flight at monday",
        "arg": {
            "mode": "flight ",
            "time": "monday "
        }
    },
    {
        "action": "booking",
        "id": "i want to book a flight at 27th jan",
        "arg": {
            "mode": "flight ",
            "time": "27th jan"
        }
    }
```
Am I doing  something wrong? Or need to upgrade something.

**Comment by rodrigopivi** [comment]
Hi, 
You installed an old version of this npm package 1.0.6 you need to update to version 1.0.7,  you should be able to just reinstall the latest version, upgrade at your npm file and try reinstalling.
