### ISSUE TITLE
How to use Chatito in angularjs

### ISSUE THREAD

**Issue by Asma-droid** [rodrigopivi/Chatito#83]
Hi all,

I would like to use chatito in angular js. Looking for the doc of chatito , i found this command
const chatito = require("chatito");
const dataset = chatito.datasetFromString(dslDefinitionString);

I would like to know how should i define the dslDefinitionString

Thanks

**Comment by rodrigopivi** [comment]
Hi,

The dslDefinitionString is just a chatito document. But you may need more arguments to be able to import other files.
There is a React example at the IDE source that is complete.

https://github.com/rodrigopivi/Chatito/blob/master/web/components/Editor/Editor.tsx#L3
