### ISSUE TITLE
Save entities for test

### ISSUE THREAD

**Issue by NikolaMr** [rodrigopivi/Chatito#93]
I've been going through the docs and haven't seen if this one is possible so I'll need your help for it. 
Is it possible to do a train/test split on entities?

For example:
There are 5 person entities:
@[person]
   Marta
   Marijo
   Nikola
   Antun
   Ivan

and do a train/test split of 4:1 on them so I can test how does the model perform on unseen entities?

Thanks for the info in advance.

Warm regards,
Nikola

**Comment by rodrigopivi** [comment]
Hi @NikolaMr ,

No particular syntax for that use case, but using an input like the described next, with a custom post processing will get you there:
```
%[intent_train]('training': '100')
    interacting with @[person#only_train]

%[intent_test]('testing': '30')
    interacting with @[person#only_train]

@[person#only_train]
    Marta
    Marijo
    Nikola
    Antun

@[person#only_test]
    Ivan
```

Cheers,
